---
title: 'Experimental Design '
author: 'ling '
date: '2021-03-26'
slug: experimental-design
categories: []
tags: []
---


Some concepts and examples in Experimental Design  


experimental study: a study subject is assigned the treatment
observational study: a study with subject is observed or measured
experimental unit: in an experimental study, basic entity can be assigned is called experimental unit. The experimental unit is people, called subject. At observational and experimental study, subjects are called participants.  


## Experimental Design

A good experimental design will need:
1. treatments are random assigned to the experimental unit.  
2. Replications: the number of the sample size in each treatment are expected to be a lot.
3. Matched paired design and block design: they are used to control the variation to the response variable.


### randomized block design  

__block__ are used on a factor considered a significance effect to the study of the relationship between the two variables. Like a reginon, gender, races etc. Once they are decided not important but have the knowing effect to the study. We better used the block design and the randomized is used with in each block. When we are reading the design, the block is a key word in the article.


### matched-pair design

for each subject has a similar subject(controlled the other factors) is assigned the treatment.
 
Example:

1. matched pair design: contain the word __pair__ .  拿用电的那个来举个例子， 用电公司想要知道改变收费的方法会不会对用电量产生印象。 然后1 方法：
3个小区，每个小区100 人，一共300 人。 根据去年的用水量的不同， 分别选择两个家庭， 一个使用strategy1 一个使用strategy 2。 然后
搜集最后的数据。 所以我们的实际的样本是150

2. block design: similar population are selected, the
3个小区， 在每个小区随机选择50 ，个人使用S1 ， 50 个人使用S2。 我们的样本实际是50 ， 但是我们控制了小区不一样对于实验结果的影响。




### Single/Double Blind
1. to subject: do you know what design you are assigned? NO/YES
2. to evalution: do you know what design the observation is assigned? NO/YES
* Single blind: one NO among 1 and 2
* Double blind: two NO among 1 and 2
* neither :  two YES among 1 and 2  

Example: the new packaging experimental design: A company decided to study if the new package will improve the amount of products sale.  Thus two packages are put two different countries.
Stores in both city(Subject) knows what package design put on it. And people in the city(evaluation) knows what package they are buying.



### A/B testing
online bank update their website: version A and version B. random assign to the customers.

response rate|Overall| female|male|
-------------|-----|-------|----|
Total| 400| 200|200
response|100| 40|60|
A|$\frac{40}{200}$ 20%| $\frac{10}{100}$ 10%|$\frac{30}{100}$ 30%|
B|$\frac{60}{200}$ 30%| $\frac{40}{100}$ 40%|$\frac{20}{100}$ 20%|

What you want to do to increase the response rate if the gender does not really important?  

assign version A to male and assign version B to female.  So, to explain, instead of the $\frac{100}{400}=0.25$ response rate. The rate will be increase to $\frac{0.40*200+0.30*200}{200+200}=0.35$



### repeated measurement: 
each subject/participant/experiment unit is measured twice or more than twice.
### replication: 
independent repeat run of each factor combination. Replication in an experiment refers to the idea that more than one experimental unit is assigned to each treatment condition.

Example:
In an experiment done at an English university, 64 students held their hands in ice water for as long as they could while repeating a swear word of their choice. The same students also held their hands in ice water for as long as they could while repeating a neutral word. For each condition, the researchers measured pain tolerance, the length of time of submersion, and physiological responses such as heart rate. The result was that the mean submersion time was longer for the students when they swore.




##  Observational Studies：  
Retrospective and Prospective Studies
Observational studies can be classified according to the relevant time frame of the data.

### Retrospective:
reviews or collects data over a past period (think past). An example of this type of study is using existing data from students' college records to examine differences in behavior patterns of high performing and low performing students.

### Prospective:
researchers follow participants into the future(think future) and record relevant events and variables. The prospective approach generally is a better procedure because people often do not remember past events accurately. A possible difficulty with a prospective study, however, is that participants may change their behavior because they know that it is being recorded.

### Cross-sectional:
A cross-sectional study is a snapshot of students at one point in time (think current or present). Data collected in a single survey to find out what activities students would like is an example of this type of study.

### longitudinal
Longitudinal studies follow participants over extended periods of time. "Cohort" or "grouping" is commonly used for these studies.

### Case–Control Studies
In a case–control study, “cases” who have a particular attribute or condition are compared to “controls” who do not. A distinguishing feature of a case–control study is that individuals are sampled within categories of the response variable (cases and controls). The idea is to compare the cases and controls to see how they differ on explanatory variables of interest.
In medical settings, the cases usually are individuals who have been diagnosed with a particular disease. Researchers then identify a group of controls who are as similar as possible to the cases except that they don’t have the disease. To achieve this similarity, researchers often use patients who have been hospitalized for other causes as the controls.



# Noted

* The results of a research study should only be extended to the population that is represented by the participants in the study.  
* Interacting variables may make the magnitude of a relationship different for different subgroups.  

| Hawthorne effect| Experimenter effects|Lack of ecological validity|
|-----------------|---------------------|---------------------------|
|experiment respond differently in the experiment|other factors affect the responses| the difference reaction because the limitation of the social/real environment
the above three effects are usually showing in the observational study and can be fixed/solved by double blinded design.


|Notation|Meanings|
|------- |-----------|
|factors | X, independent variable(categorical), explanatory variable(categorical) |
|treatments| combination (组合) Factor1(2 level),actor2(3 levels) total has 2*3 = 6 |
|level|  the categorizes in each factor|

### Example:
 It designs an experiment to consider the effects that temperature and humidity have on its production rate. It will test at three different temperatures seven different humidity levels.  
 
* Factor: the temperature and humidity.  
* Treatment: the combination of the different combination of tempurature and humidity.    
* level: in each factor, like humidity: I, II, III; or tempurature: low, middle, high.   

***

[reference](https://www.amazon.com/Mind-Statistics-Standalone-Jessica-Utts/dp/1285463188)


