---
title: 'Untitle'
author: ''
date: '2021-04-11'
slug: 'Untitle'
categories: []
tags: []
output:
  blogdown::html_page:
    toc: true
    toc_depth: 3
    css: "/css/my-style.css"
---


To find a job is extremely painful especially you are meeting a huge information. In order to save time, I decide to make it as a produre to follow. Narrow the area: data analysis, data science, etc. Hard skills: R, Python, SAS.  

1. Look at the company name. And answer the following questions.
  * what is the name of the company, who is hiring if it provides(people or department)
  * what is the mainly job duty? try to minimize to 3 bullet points 
  * what is the requirement? check the percentage of the Required Knowledge & Experience you have satisfied. I know it is unlikely to achieve all the requests but pay attention to those with the __strong__ verb, must have , at least, etc. If you are 60% good with it, go ahead and go the section 2. if you are not sure the requirements then just close the pages. If you like the job sososos much, please see the requirments and list a plan to learn the skills requires but skill close the  as there is huge chance you are wasting time when applying. 

2. Look at how to apply: apply through career website or apply through the official website (the link is usually provided). Prepare the materials.
  * the skills try match the requirement 
  * change some word in the experience.
  
--- 

## Decision Tree

use for classification and regression. Depends on the loss function. 

Classification:

Regression:



Pruning: avoid over-fitting, we can change the `ccp_alpha` to change the prun.




## HackerRank

Use the HackerRank for the coursa interver. There are totally 10 some question. The first includes some statistics question with bayse and retension rate


## vue meeting 
some questions are for your preparation: some questions are asked in terms of the 
 
## contigency table 

Precision and Recall

## leedcode 




## report of from the $X_t$,$y_t$ are good performance. But has high false positive rate in the testing data. Why?

recommend to check the current threshold 0.5 in his logistic regression classifier

## random forest are able to reduce the variance 

A. training on different sample of data 
B. use random subset of features 

tree belongs to bagging and bagging is used average the noise to reduce the variance. 

## a plot x (epoch), y(loss) group by the different learning rate: 01, and 1e-10. the first group decrease and increasing at one point, the second decrease steeply and converge at a certain point. 

the explanation of the quick converge of the small learning rate: 
learning rate = 0.1 means , in each learning, the model changed the parameter by 0.1 and 
1 epoch means go through the entire training dataset once. In this case, we will choose the learning rate close to the one converges. 

## people think deep leanring can get better performance so he built layers of neural networks. How to get start? 
The last layer he uses sigmoid, the output then will be used as probability of class 1

## how to pick the esamble size? 

According to the "the law of diminishing returns in ensemble construction." pick the same amount of classifier can give the higher accuracy.           

## assumption for the linear regression

Linearity: The relationship between X and the mean of Y is linear.
Homoscedasticity: The variance of residual is the same for any value of X.
Independence: Observations are independent of each other.
Normality: For any fixed value of X, Y is normally distributed.

## residual and error

An error is the difference between the observed value and the true value (very often unobserved, generated by the DGP). 
A residual is the difference between the observed value and the predicted value (by the model).
