---
title: SAS
author: 'ling '
date: '2021-03-21'
slug: sql-sas
categories: []
tags: []
---


# SQL 
You are given two non-empty linked lists representing two non-negative integers. 

The digits are stored in reverse order, and each of their nodes contains a single digit. 

Add the two numbers and return the sum as a linked list.

You may assume the two numbers do not contain any leading zero, except the number 0 itself.

[source](https://people.stat.sc.edu/hitchcock/)

1.  For this problem we will begin with the sashelp.baseball data set.

(a) Create a new table called newtable in the work library  that has exactly the same rows as the sashelp.baseball table,
but only has the following columns: ABCD
```
proc sql outobs = 10;
  title '';
  create table sql.newtable as
      select A,
             B,
             C,
             D
      from sql.baseball;
quit;
```

(b) Insert the following two rows into the table
```
proc sql;
insert into newtable
(A,B,C,D)
values(1,2,3,4);
insert into newtable
(A,B,C,D)
values(1,2,2,2);
select * from newtable;
quit;
```

(c) Add three different types of *integrity constraint* to the table.  Verify that each integrity constraint 
works by attempting to insert rows that fail each respective constraint.  In your program's comments, report the 
result of the attempted insertions.

```
create table 
  (col1 type
   col2 type2,
   col3 type3,
   /*          */
    constain col1 primary key(stats),
    constrain population check(col1 gt 0),
    constrain continent check(col2 in ()));

```

```
proc sql;
insert into new_table
(Col1, Col2, Col3)
values(1,2,3);
* fails Col1 not null constraint;
* fails primary key constraint;
* fails League check constraint;
quit;
```

(d) Convert the col A with .


_NOTE_:  
the case when in sql is (case when ) as 
        in sas sql is var = (case when )
        
```
proc sql outobs = 10;
update table
# create a fuction as a filer to filer out 
set modsal =  
case when B= 1 then 6*A
     when B= 2 then 5*A
     when B= 0 then 8*A 
else 0*A
end; 
select *
from newtable;
quit;
```

2. Two data with labled 'practice vertical table'. the data describe observations with same variable in two different years.
Use PROC SQL __set operation__ commands to do the following:

(a) Write a query that will combine the tables into one table that has all the players who played in both years. Select only the "Col1", "Col2" and "Col3" columns: formated date into MMDDYY10 to be printed.  and ordered by the 'Col3'

```
select Col1,Col2,Col3
from 2014
intersect
select Col1, Col2, Col3
from 2015
order by rating desc
quit;
```

(c) Write a query that will combine the tables into one table that has all the players who played in 2015 but not in 2014.  
```
proc sql;
select Col1, Col2, Col3
from 2015 
except 
select Col1, Col2, Col3
from 2014 
quit;
```

(d) Write a query that will combine the tables into one table that has all the players who played in either 2014 or 2015 or both years.  
```
proc sql;
select col1, col2, col3.
from 2014
union
select col1,col2,col3
from 2015
quit;
```

(e) Do the same as in part (d), but for players who played in both years, have them be listed 
multiple times (i.e., as many times as they appear in the tables).

```
proc sql;
select Col1, Col2, Col3
from 2014
union all
select Col1, Col2, Col3
from 2015
quit;
```
# MRCRO



