---
title: cv+resume
author: ''
date: '2021-04-22'
slug: resume
categories: []
tags: []
output:
  blogdown::html_page:
    toc_depth: 3
    css: "/css/my-resume.css"
---
To who may read

I am writing to express my keen interest in the Research Analysis I in SickKids hospital, CIHR SUBINT Tam to Hahn.

I graduated from biostatistics program in University of Toronto in year 2018. I respect the impact of gene and environment and try single healthy experiment on myself to understand some hard theories. After graduation, I worked in the industry for 1+ year and decided to change my focus on researching the methodology health related. My working motivation is to help PI or doctor better treat patients by ensure the high quality analysis. 

best,

Ling Lin  
ytlinglin@gmail.com  
750 bay street , M5G 1N6  
416-841-1903

# KEY

- Master in a biostatistics. 
- Experience with parametric and no parametric stimulation study. 
- Experience in experimental design, sample size calculation, Analysis of Variance(ABtesting), time series analyses etc.  
- Experience with computer programming (Python, or R).
- Be able to work independently and meet deadlines. 

# PROFESSIONAL EXPERIENCE

## Senior Data Analyst, TD Securities

### 2020.May-2020.Dec

Participated in the planning, development, deployment and testing of large-scale information in PRD environment. Cooperated in project focused on building dashboards for detecting data accuracy and performing quality checks. Automated scheduled report with python script and performing ac hoc analyses and data extraction. Maintained and updated End of Day batch files and ensure the functionality of the scheduled jobs by catching any API initialization issues.


## Data Analyst, TD Securities

### 2019.Sep-2020.Apr

Worked on a research project by implementing an algorithm to auto allocate asset, maximizing the sharp ratio by using historical data from TSX using Python. Built dashboards to deliver data accuracy and data quality checks on the fly.

## Research Analysis, Public Health Ontario
### 2018.Nov-2019.Jun

Assisted scientists to work on a CIHR funded project analyze the 2004 and 2015 from the Canadian Community Health Survey from 2015. Cleaned the survey data and subtracted the cohorts of children in age 3-19 from database system with SAS(SQL). Determined the appropriate model and implemented the NCI SAS Marco model to estimate the distribution of the real sodium intake and examined the association of sodium consumption of children across parental education

# PRESENTATION
## How To Automate Cells Counting From Microscopic Images  
### 2019 Summer
This data set contains 3,600 images and were randomly assigned to 2,400 images in 
training set and 1,200 images in validation set. Predicted the number of cells with give 
black and white pictures with Le-net architecture in Keras Library. Modelled with stain 
level (2 levels) stratification prediction accuracy achieved 89.1 percent. 

## Can a Newly Published TED Talk Become Popular in The Future
### 2018 Summer
The data are from TED and extracted from the ted talk website with the different formats, 
with 2550 observations and 17 variables. Transformed the raw data for descriptive 
analysis. Applied logistics regression along with both LASSO shrinkage method and 
Forward/Backward Step wise method to select features. Compared the result with output 
from Neural Network

# EDUCATION
* University of Toronto, Biostatistics, Master of Science
* York University, Statistics, Bachelor of art, (Honor degree)